### ISSUE TITLE
Fighter import - Unexpected app. closing

### ISSUE THREAD

**Issue by Hitoride57** [Maus3rSR/Hajime#20]
OS : Ubuntu 18.04 XFCE

Cancelling fighters import by closing OS window to select CSV file by using "Cancel" button or upper right window close button make app entirely close.

![Capture d’écran_2020-10-18_11-33-27](https://user-images.githubusercontent.com/69247004/96363720-2e711080-1136-11eb-9efe-e7119331e2b2.png)

**Comment by Maus3rSR** [comment]
I can not reproduce this issue on VM with same Linux version. Everything is OK. Maybe because I upgraded a dependancy version (electron) which handle GUI and fixed this issue.

I'll close it for the moment. I'll release a new version later.
