### ISSUE TITLE
Naginata - Adapt the software to competitions needs

### ISSUE THREAD

**Issue by Maus3rSR** [Maus3rSR/Hajime#23]
### What's different with Kendo

There is one more score possible in Naginata:
* Sune (shin)

### What other things we need to adapt

We should have some **templates** system we can switch with software settings. I think when we create a competition we can select whats kind of martial art it concern.

So we can adapt things like the scores, the background image and so on...

### Contact
[Mark Alexander Berghaan](https://www.facebook.com/berghaan/) _ETD Naginata_

**Comment by dragon2ag** [comment]
You might want to create also another template for Iaido

**Comment by Maus3rSR** [comment]
@dragon2ag I agree, however I need all specifications and differences from Kendo competitions to think about a good way to implement it. I do not know about this specifications
